import React, {useState, useEffect} from 'react';

import {Loader, Card, FormField} from '../components';

const Home=()=>{

    const [loading, setLoading] = useState(true);
    const [allPosts, setAllPosts] = useState(null);


    return (
        <section className="max-w-7xl mx-auto">
            <div>
                <h1 className="font-extrabold text-[#22328] text-[32px]">The Community Showcase</h1>
                <p className=" mt-2 text-[#666e75] text=[12px] max-w[500px]">Browser through a collection of imaginative and visually stunnning images generated by DALLE</p>
            </div>


            <div className="mt-16">
                <FormField/>
            </div>

            <div className="mt-10">
                {loading ?(
                    <div className="flex justify-center items-center">
                        <Loader/>
                    </div>
                    
                ):(
                    <>

                    </>
                )}
                
            </div>

        </section>

    )
}

export default Home;